### ISSUE TITLE
Print out crops table cells in multi-page documents

### ISSUE THREAD

**Issue by mstarke** [hicknhack-software/redmine_hourglass#56]
Print outs in every browser (except Firefox) are cropped along table rows. There seems to be a solution for this, if one adds the following rules:

```css
table,
table tr td,
table tr th {
	page-break-inside: avoid;
}
```
